#!/usr/bin/env node
/*
 * Generates catalog/projects.generated.yaml with one Backstage Component per Unleash project
 * that the service-account token can see. The set of projects therefore reflects exactly the
 * SA's role/access on the Unleash instance.
 *
 * Reads the same configuration the Backstage Unleash plugin uses:
 *   UNLEASH_URL       instance base url, WITHOUT /api (e.g. https://us.app.unleash-hosted.com/xxx)
 *   UNLEASH_API_TOKEN service-account token, sent verbatim in the Authorization header
 *
 * On any failure it writes a valid (empty) catalog file and exits 0 so Backstage still boots —
 * the warning explains what went wrong.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, '..', 'catalog', 'projects.generated.yaml');

const HEADER = `# AUTO-GENERATED by scripts/generate-catalog.mjs at container start. Do not edit by hand.
# One Component per Unleash project visible to the configured service-account token.
`;

// Entity names allow [a-zA-Z0-9] plus [-_.]; sanitise anything else.
const safeName = id => `unleash-${String(id).replace(/[^a-zA-Z0-9._-]/g, '-')}`;

const yamlString = value => JSON.stringify(String(value));

function renderComponent(project) {
  const title = project.name || project.id;
  const description = project.description
    ? `Unleash project ${yamlString(project.id)} — ${yamlString(project.description)}`
    : `Unleash project ${yamlString(project.id)}`;
  return `---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${safeName(project.id)}
  title: ${yamlString(title)}
  description: ${description}
  annotations:
    unleash.io/project-id: ${yamlString(project.id)}
spec:
  type: service
  lifecycle: production
  owner: guests
`;
}

async function write(body) {
  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, HEADER + body, 'utf8');
}

async function main() {
  const base = (process.env.UNLEASH_URL || '').replace(/\/+$/, '');
  const token = process.env.UNLEASH_API_TOKEN || '';

  if (!base || !token) {
    console.warn(
      '[generate-catalog] UNLEASH_URL and/or UNLEASH_API_TOKEN are not set — writing an empty catalog.',
    );
    await write('');
    return;
  }

  const url = `${base}/api/admin/projects`;
  let projects = [];
  try {
    const res = await fetch(url, {
      headers: { Authorization: token, Accept: 'application/json' },
    });
    if (!res.ok) {
      throw new Error(`GET ${url} -> ${res.status} ${res.statusText}`);
    }
    const data = await res.json();
    // Admin API returns { projects: [...] }; tolerate a bare array too.
    projects = Array.isArray(data) ? data : data.projects || [];
  } catch (err) {
    console.warn(
      `[generate-catalog] Failed to list Unleash projects (${err.message}). Writing an empty catalog; ` +
        'check UNLEASH_URL/UNLEASH_API_TOKEN and the token permissions.',
    );
    await write('');
    return;
  }

  if (projects.length === 0) {
    console.warn(
      '[generate-catalog] The service account can see 0 projects — writing an empty catalog.',
    );
    await write('');
    return;
  }

  const body = projects.map(renderComponent).join('');
  await write(body);
  console.log(
    `[generate-catalog] Wrote ${projects.length} project component(s): ${projects
      .map(p => p.id)
      .join(', ')}`,
  );
}

main().catch(async err => {
  console.warn(`[generate-catalog] Unexpected error: ${err.stack || err}`);
  await write('');
});
